ohler55/ox

lib/ox.rb
Thanks for solving the issue #104. It seems there is one more file with the previous BSD license. It's a detail, but sending the pull request.
=> set license to MIT

README.md
I'm assuming it's a copy and paste error. Looking into the code, Ox is still current for the XML de(serializer) :)
=> Replace Oj namespace with Ox

ext/ox/builder.c, test/tests.rb
If using `Ox::Builder`, passing a string with a newline character in it to `Ox::Builder#raw` or `Ox::Builder#cdata` would result in an infinite loop.
=> Fix infinite loops in Builder caused by newlines

lib/ox/element.rb, lib/ox/instruct.rb
`Element` and `Instruct` both inherit from `Node`. They then override `Node#eql?` to include additional behavior, but still call `super` for the basic check, which makes the lines I removed be redundant.
=> Removed unnecessary lines

ext/ox/sax.c, test/sax/smart_test.rb
Looks like a copy & paste bug. Thanks for the new `nest_ok` option!
=> Fix segfault on non closed elements with overlayer set to nest_ok

ext/ox/ox.c
The docs are missing the `:skip_none` option for the `sax_parse` and `sax_html ` methods.
=> Add info about skip_none option to docs

.travis.yml, CHANGELOG.md, ext/ox/ox.c, ext/ox/ox.h, ext/ox/parse.c, ext/ox/sax.c, lib/ox/version.rb
Added skip_off mode that turns off all skipping of whitespace. Even all white space strings will be included in the SAX parsing.
=> New :skip_off mode

lib/ox/element.rb, test/tests.rb
In the current implementation the search pattern `?[@attribute]` is not working as expected:
```rb
parent = Ox::Element.new('Parent')
son_with_job = Ox::Element.new('Son').tap do |n|
n['job'] = 'a job'
parent << n
end
son_without_job = Ox::Element.new('Son').tap { |n| parent << n }
daughter_with_job = Ox::Element.new('Daughter').tap do |n|
n['job'] = 'another job'
parent << n
end
parent.locate('?[@job]')
=> [son_with_job, son_without_job, daughter_with_job]
```
The hack I needed to implement to look into sub-nodes was:
```rb
result = parent.locate('Something').select |n1|
n1['attribute'] || n1[:attribute]
end.flat_map |n2|
n2.locate('SomethingElse')
end
```
Thanks to this pr it will be possible to check the attribute presence when a value is not specified for a given node attribute:
```rb …
```
=> Allow locate based on attribute presence

ext/ox/dump.c, lib/ox/version.rb
We found some problem in `v2.9.3`
> related with: https://github.com/ohler55/ox/issues/215
-------- how it was
when 
output is empty 
and 
indent is set to -1
we got previous dumb_obj_to_xml result
--------
so I think that we should dump_value almost empty to fix this edge case
=> Fix empty output with negative indent problem - not terminated buffer at start

ext/ox/builder.c, ext/ox/dump.c, ext/ox/err.h, ext/ox/gen_load.c, ext/ox/ox.c, lib/ox/error.rb, test/tests.rb
Ox currently raises a `SyntaxError` when certain invalid XML is encountered (for instance, if a the document contains a prolog that is not the first element.)  Typically, `SyntaxError` is raised by the Ruby interpreter when code with invalid syntax is encountered.  From that standpoint, it is an unexpected error for Ox to be raising.  Additionally, `SyntaxError` does not inherit from `StandardError`, meaning that it must be explicitly rescued (or `Exception` must be rescued) and a bare rescue statement will not capture the error.  This behavior has tripped me up multiple times.
This change replaces Ox's use of `SyntaxError` with a new `Ox::SyntaxError` class that does inherit from `StandardError` and will be more natural for developers to work with.
I recognize that this is a breaking …
=> Introduce an Ox::SyntaxError class

lib/ox/element.rb
For Ox elements, `name` is an alias of `value`.
When renaming an element, only `value=` was working.
This PR makes `name=` work as well.
https://stackoverflow.com/questions/913349/what-is-the-best-way-to-create-alias-to-attributes-in-ruby
=> Fix issue with name/value alias for elements

lib/ox/element.rb
This allows for an easy use of Enumerable methods
like `#reduce` or `#map` by chaining them after
`#each` call.
Enumerable can be included to remove the extra call
but that would add methods to a class that intends
to use methods for navigation. Making `<reduce>` child
inaccessible with `#reduce` call, for example.
=> Make `Ox::Element#each` return an Enumerator

examples/sax_ractor.rb, ext/ox/extconf.rb, ext/ox/ox.c, ext/ox/sax.c
For https://github.com/ohler55/ox/issues/277
I've been experimenting with `Ractor`s since upgrading to Ruby 3.0 for https://github.com/ohler55/ox/issues/275 but quickly ran into `Ractor::UnsafeError` when trying to call `Ox::sax_parse` in anything except the main `Ractor`.
Per Ruby's `Ractor` C extension documentation (link below):
"By default, all C extensions are recognized as `Ractor`-unsafe. If C extension becomes `Ractor`-safe,
the extension should call `rb_ext_ractor_safe(true)` at the `Init_` function and all defined method marked as `Ractor`-safe. `Ractor`-unsafe C-methods only been called from main-ractor. If non-main ractor calls it, then `Ractor::UnsafeError` is raised."
I don't like to open seemingly-large feature requests like this without making some attempt at it myself …
=> Mark `Ox::sax_parse` as `Ractor`-safe and add a `Ractor`-based `Ox::Sax` example.

ext/ox/builder.c, test/tests.rb
First of all, thank you for the great gem and for keeping it easy to use.
I ran into a situation where the [XML file format](https://www.gala-global.org/tmx-14b) I'm generating has some requirements regarding the formatting, especially the whitespaces.
<details>
<summary>TMX specific details</summary>
[`<seg>` specifications](https://www.gala-global.org/tmx-14b#seg)
> ... All spacing and line-breaking characters are significant within a `<seg>` element.
</details>
In order to generate a human-readable XML, I'd like to keep the indentation for the rest of the file, and only switch the indentation off when the given node is being open.
This is my first contribution to a C extension, so let me know if I need to make changes to the `.c` file or if you think more testing is needed.
=> Add getter and setter for the indent value of `Ox::Builder`

ext/ox/builder.c, ext/ox/intern.c, ext/ox/sax_as.c, test/tests.rb
warning: undefining the allocator of T_DATA class Ox::Cache
warning: undefining the allocator of T_DATA class Ox::Sax::Value
See: https://bugs.ruby-lang.org/issues/18007
Order of dumped XML elements changed in a test, but I believe the change is not significant.
=> Resolve Ruby 3.2 "undefining the allocator of T_DATA class" warnings

lib/ox.rb
Fixed https://github.com/ohler55/ox/issues/300
RubyGems 3.4 cleaned-up build artifact automatically. We should use `require_relative` from `ox.rb` without `ext` directory.
=> Load C extension with require_relative

README.md
The shields.io badge is currently broken because of https://github.com/badges/shields/issues/8671.
Could update to use their new syntax, but just swapped it to the built-in markup for Actions
=> chore: use GitHub Actions badge markdown

.github/workflows/CI.yml
3.2 is probably the same as the HEAD right now, but probably good to be explicit
=> Add explicit 3.1 and 3.2 Ruby version to CI matrix

.rubocop_todo.yml, ox.gemspec
https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecrequiredrubyversion
Went by the currently tested version in CI, but wasn't sure if it was intentional to support the EOL 2.5, 2.6, and (soon) 2.7 versions, but left it as-is
=> Enable Rubocop Gemspec/RequiredRubyVersion

.rubocop_todo.yml, examples/saxy_html.rb, test/sample.rb, test/sax/sax_test.rb, test/sax/smart_test.rb
Figured it might be easier to look just at the Array rule changes instead of th large block in Batch 4.
I did a quick find/replace for `[[` -> `[\n[` and reformatted to try and address the wrapping from the other PR
=> Autofix Rubocop Array cops

.github/workflows/CI.yml, .gitignore, Rakefile, ox.gemspec, test/tests.rb
Seems that several steps should be taken to invoke the tests for ox gem.
Since it is easy to make a mistake for me, this patch will invoke the tests with the `rake` command only.
=> Add rake task in order to invoke tests

ext/ox/dump.c, ext/ox/extconf.rb, ext/ox/obj_load.c, ext/ox/ox.c, ext/ox/ox.h, ext/ox/sax_as.c
Currently, ox gem has supported Ruby 2.7 or later.
https://github.com/ohler55/ox/blob/52ff373b759fcf7bc95a09163139f8fdd21c2a26/ox.gemspec#L29
The APIs introduced in older Ruby are free to use.
- rb_obj_encoding() was introduced at Ruby 1.9.0
- https://github.com/ruby/ruby/commit/19dee8af57634c5813286ffbb63cc82611748378
- rb_struct_alloc_noinit() was introduced at Ruby 1.9.0
- https://github.com/ruby/ruby/commit/0d8956725284206788bae5fbd6ed032f186ad366
- rb_ivar_foreach() was introduced at Ruby 1.9.0
-  https://github.com/ruby/ruby/commit/5c0e68c39c3fc7717311826549a30d1615eb2007
- rb_time_timespec() was introduced at Ruby 2.3.0
- https://github.com/ruby/ruby/commit/f1df08e76deadd8a22dc53b86d68cad5f6c11c22
- rb_time_nano_new() was introduced at Ruby 1.9.0
- …
=> Clean up by removing CRuby API checks that are no longer needed

ext/ox/builder.c, ext/ox/dump.c, ext/ox/ox.c
RUBY_INTEGER_UNIFICATION was introduced at Ruby 2.4.0. https://github.com/ruby/ruby/blob/8c6b349805e2f17a57576b8dfad31e5681d6b0e9/doc/NEWS/NEWS-2.4.0#compatibility-issues-excluding-feature-bug-fixes-
Now, ox gem supports Ruby 2.7.0 or later.
So, this patch will remove unnecessary code for old Ruby.
=> Clean up RUBY_INTEGER_UNIFICATION

ext/ox/gen_load.c, ext/ox/ox.c, ext/ox/ox.h
There is an API to get a Symbol object from a String object.
The same API is eventually called with rb_funcall(), but it might have some overhead. https://github.com/ruby/ruby/blob/master/string.c#L11988
=> Use rb_str_intern() to get symbol instead of rb_funcall()

ext/ox/dump.c, ext/ox/gen_load.c, ext/ox/obj_load.c, ext/ox/ox.c
T_COMPLEX and T_RATIONAL were introduced at Ruby 1.9.0 https://github.com/ruby/ruby/commit/6125552c27b40a8da9e162af2655feca82ac16d3
RB_GC_GUARD was introduced at Ruby 1.9.0
https://github.com/ruby/ruby/commit/46603a78afde1386f92b38f9b16ca86daa93ad88
=> Remove unnecessary check for T_COMPLEX, T_RATIONAL and RB_GC_GUARD

ext/ox/builder.c, ext/ox/dump.c, ext/ox/obj_load.c, ext/ox/ox.c, ext/ox/ox.h, ext/ox/slotcache.c, test/c/cache16.c, test/c/cache_test.c
rb_String() will convert to String object using #to_s method if needed.
https://github.com/ruby/ruby/blob/8b2884c0b51e4733c09ecbb388ca1b236bad738b/object.c#L3825-L3831
=> Use rb_String() instead of rb_funcall()

ext/ox/ox.c
It looked up one by one to make sure that the supported options were included in passed options. This approach of looking up the passed hash each time has an overhead.
This patch will extract key and value from the passed options using `rb_hash_foreach()` and check if they are supported or not.
−            | before   | after    | result
--            | --       | --       | --
load          | 640.171k | 679.986k | 1.062x
- MacBook Pro (M1, 2021)
- macOS 13.3.1
- Apple M1
- clang 14.0.3
- Ruby 3.2.2
```
Warming up --------------------------------------
load    63.538k i/100ms
Calculating -------------------------------------
load    640.171k (± 0.2%) i/s -      3.240M in   5.061851s
```
```
Warming up --------------------------------------
load    67.690k i/100ms
Calculating …
```
=> Optimize parsing option args in load

ext/ox/obj_load.c
It has already checked the type under `RUBY_T_FIXNUM != rb_type(h->obj)` conditions in https://github.com/ohler55/ox/blob/83eca82be8f1bae9eb453cf12ad26f057ca9c6c8/ext/ox/obj_load.c#L649
So this patch will check the type of `ph->obj` instead.
=> Fix type check for RationalCode

Gemfile, Rakefile, ox.gemspec
Since Ruby-HEAD fails to load some gems, this patch gives `bundle exe` so that gems are loaded via bundler.
Similar with https://github.com/ohler55/oj/pull/924
This PR requires https://github.com/ohler55/ox/pull/355
=> CI: Fix CI error

ox.gemspec
The bigdecimal gem will be changed bundled gem since Ruby 3.4.0. https://www.ruby-lang.org/en/news/2023/09/14/ruby-3-3-0-preview2-released/
To use bundled gem, it requires to specify the dependency in Gemfile.
Similar with https://github.com/ohler55/oj/pull/901
=> Add bigdecimal as dependency gem

ext/ox/builder.c, ext/ox/cache.c, ext/ox/cache.h, ext/ox/intern.c, ext/ox/parse.c, ext/ox/sax.c, ext/ox/sax.h, ext/ox/sax_as.c
When compile ox gem with Ruby 3.4-dev, it show the following deprecated messages:
```
../../../../ext/ox/builder.c:356:29: warning: 'rb_data_object_wrap_warning' is deprecated: by TypedData [-Wdeprecated-declarations]
356 |         volatile VALUE rb = Data_Wrap_Struct(builder_class, NULL, builder_free, b);
|                             ^
/Users/watson/.rbenv/versions/3.4-dev/include/ruby-3.4.0+0/ruby/internal/core/rdata.h:199:5: note: expanded from macro 'Data_Wrap_Struct'
199 |     rb_data_object_wrap(                          \
|     ^
/Users/watson/.rbenv/versions/3.4-dev/include/ruby-3.4.0+0/ruby/internal/core/rdata.h:363:31: note: expanded from macro 'rb_data_object_wrap'
363 | #define rb_data_object_wrap   RUBY_MACRO_SELECT(rb_data_object_wrap_2, RUBY_UNTYPED_DATA_WARNING)
| …
```
=> Use TypedData_Wrap_Struct() macro to suppress deprecated messages

ext/ox/intern.c, ext/ox/obj_load.c, ext/ox/ox.c, ext/ox/sax_as.c, ext/ox/sax_hint.c, ext/ox/special.c
This patch will suppress following warning message when compile ox with gcc
```
$ cd ext/ox
$ ruby extconf.rb
$ make
...
intern.c: In function 'ox_hash_init':
intern.c:70:6: warning: old-style function definition [-Wold-style-definition]
70 | void ox_hash_init() {
|      ^~~~~~~~~~~~
...
```
=> Suppress "old style definition" warning

ext/ox/sax_buf.c
This patch will suppress the following warning with compiling gcc:
```
sax_buf.c: In function 'read_from_str':
sax_buf.c:201:5: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-truncation]
201 |     strncpy(buf->tail, buf->in.str, cnt);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sax_buf.c:197:11: note: length computed here
197 |     cnt = strlen(buf->in.str) + 1;
|           ^~~~~~~~~~~~~~~~~~~
```
If strncpy is used, we should pass count argument as a value of source boundary.
In this case, it might be `strncpy(buf->tail, buf->in.str, max);`
This patch will use `memcpy` instead becaseu copied length is already known.
Ref. https://stackoverflow.com/a/56782476
=> Suppress "warning: 'strncpy' specified bound depends on the length of the source argument"
